# make local-image-ice-demo
# docker run --rm -it ice-demo:local q interquery

FROM golang:1.21-alpine3.18 as builder

RUN set -eux; apk add --no-cache git libusb-dev linux-headers gcc musl-dev make go;

ENV GOPATH=""

COPY go.mod .
COPY go.sum .
COPY Makefile .

RUN go mod download

COPY ./testing/demo-simapp .

RUN make build

FROM alpine:3.18

COPY --from=builder /go/build/* /bin/ice-demo

ENTRYPOINT ["/bin/ice-demo"]