// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ice/v1/packet.proto

package types

import (
	fmt "fmt"
	_ "github.com/cometbft/cometbft/abci/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type InterchainPacketAck_Type int32

const (
	InterchainPacketAck_REGISTER   InterchainPacketAck_Type = 0
	InterchainPacketAck_UNREGISTER InterchainPacketAck_Type = 1
	InterchainPacketAck_EVENT      InterchainPacketAck_Type = 2
)

var InterchainPacketAck_Type_name = map[int32]string{
	0: "REGISTER",
	1: "UNREGISTER",
	2: "EVENT",
}

var InterchainPacketAck_Type_value = map[string]int32{
	"REGISTER":   0,
	"UNREGISTER": 1,
	"EVENT":      2,
}

func (x InterchainPacketAck_Type) String() string {
	return proto.EnumName(InterchainPacketAck_Type_name, int32(x))
}

func (InterchainPacketAck_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_094017127cbec1c8, []int{3, 0}
}

// InterchainRegisterPacket is comprised of an event to listen for.
type InterchainRegisterPacket struct {
	// event defines the name of the event listen for.
	Event string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// memo is optional
	Memo string `protobuf:"bytes,2,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (m *InterchainRegisterPacket) Reset()         { *m = InterchainRegisterPacket{} }
func (m *InterchainRegisterPacket) String() string { return proto.CompactTextString(m) }
func (*InterchainRegisterPacket) ProtoMessage()    {}
func (*InterchainRegisterPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_094017127cbec1c8, []int{0}
}
func (m *InterchainRegisterPacket) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InterchainRegisterPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InterchainRegisterPacket.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InterchainRegisterPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterchainRegisterPacket.Merge(m, src)
}
func (m *InterchainRegisterPacket) XXX_Size() int {
	return m.Size()
}
func (m *InterchainRegisterPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_InterchainRegisterPacket.DiscardUnknown(m)
}

var xxx_messageInfo_InterchainRegisterPacket proto.InternalMessageInfo

func (m *InterchainRegisterPacket) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *InterchainRegisterPacket) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

// InterchainUnregisterPacket is comprised of raw query.
type InterchainUnregisterPacket struct {
	// event defines the name of the event to stop listening for.
	Event string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// memo is optional
	Memo string `protobuf:"bytes,2,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (m *InterchainUnregisterPacket) Reset()         { *m = InterchainUnregisterPacket{} }
func (m *InterchainUnregisterPacket) String() string { return proto.CompactTextString(m) }
func (*InterchainUnregisterPacket) ProtoMessage()    {}
func (*InterchainUnregisterPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_094017127cbec1c8, []int{1}
}
func (m *InterchainUnregisterPacket) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InterchainUnregisterPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InterchainUnregisterPacket.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InterchainUnregisterPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterchainUnregisterPacket.Merge(m, src)
}
func (m *InterchainUnregisterPacket) XXX_Size() int {
	return m.Size()
}
func (m *InterchainUnregisterPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_InterchainUnregisterPacket.DiscardUnknown(m)
}

var xxx_messageInfo_InterchainUnregisterPacket proto.InternalMessageInfo

func (m *InterchainUnregisterPacket) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *InterchainUnregisterPacket) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

// InterchainEventPacket is comprised of raw query.
type InterchainEventPacket struct {
	// event defines the name of the event that occurred.
	Event InterchainEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event"`
	// memo is optional
	Memo string `protobuf:"bytes,3,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (m *InterchainEventPacket) Reset()         { *m = InterchainEventPacket{} }
func (m *InterchainEventPacket) String() string { return proto.CompactTextString(m) }
func (*InterchainEventPacket) ProtoMessage()    {}
func (*InterchainEventPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_094017127cbec1c8, []int{2}
}
func (m *InterchainEventPacket) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InterchainEventPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InterchainEventPacket.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InterchainEventPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterchainEventPacket.Merge(m, src)
}
func (m *InterchainEventPacket) XXX_Size() int {
	return m.Size()
}
func (m *InterchainEventPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_InterchainEventPacket.DiscardUnknown(m)
}

var xxx_messageInfo_InterchainEventPacket proto.InternalMessageInfo

func (m *InterchainEventPacket) GetEvent() InterchainEvent {
	if m != nil {
		return m.Event
	}
	return InterchainEvent{}
}

func (m *InterchainEventPacket) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

// InterchainRegisterPacket is comprised of an event to listen for.
type InterchainPacketAck struct {
	Type InterchainPacketAck_Type `protobuf:"varint,1,opt,name=type,proto3,enum=ice.v1.InterchainPacketAck_Type" json:"type,omitempty"`
}

func (m *InterchainPacketAck) Reset()         { *m = InterchainPacketAck{} }
func (m *InterchainPacketAck) String() string { return proto.CompactTextString(m) }
func (*InterchainPacketAck) ProtoMessage()    {}
func (*InterchainPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_094017127cbec1c8, []int{3}
}
func (m *InterchainPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InterchainPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InterchainPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InterchainPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterchainPacketAck.Merge(m, src)
}
func (m *InterchainPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *InterchainPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_InterchainPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_InterchainPacketAck proto.InternalMessageInfo

func (m *InterchainPacketAck) GetType() InterchainPacketAck_Type {
	if m != nil {
		return m.Type
	}
	return InterchainPacketAck_REGISTER
}

func init() {
	proto.RegisterEnum("ice.v1.InterchainPacketAck_Type", InterchainPacketAck_Type_name, InterchainPacketAck_Type_value)
	proto.RegisterType((*InterchainRegisterPacket)(nil), "ice.v1.InterchainRegisterPacket")
	proto.RegisterType((*InterchainUnregisterPacket)(nil), "ice.v1.InterchainUnregisterPacket")
	proto.RegisterType((*InterchainEventPacket)(nil), "ice.v1.InterchainEventPacket")
	proto.RegisterType((*InterchainPacketAck)(nil), "ice.v1.InterchainPacketAck")
}

func init() { proto.RegisterFile("ice/v1/packet.proto", fileDescriptor_094017127cbec1c8) }

var fileDescriptor_094017127cbec1c8 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xc1, 0x6a, 0xf2, 0x40,
	0x14, 0x85, 0x13, 0xff, 0x28, 0xbf, 0xb7, 0x45, 0x64, 0xb4, 0x54, 0x2c, 0xa4, 0xe2, 0xaa, 0x8b,
	0x36, 0x83, 0xda, 0x17, 0xa8, 0x34, 0x16, 0x37, 0x52, 0x52, 0xed, 0xa2, 0xab, 0x26, 0xe3, 0x25,
	0x0e, 0x36, 0x99, 0x90, 0x8c, 0x82, 0xd0, 0x87, 0xe8, 0x63, 0xb9, 0x74, 0xd9, 0x55, 0x29, 0xfa,
	0x22, 0x25, 0x13, 0x51, 0xb1, 0xbb, 0xee, 0xe6, 0x9e, 0x7b, 0xe6, 0x3b, 0x70, 0x0f, 0x54, 0x38,
	0x43, 0x3a, 0x6f, 0xd1, 0xc8, 0x65, 0x53, 0x94, 0x56, 0x14, 0x0b, 0x29, 0x48, 0x81, 0x33, 0xb4,
	0xe6, 0xad, 0x7a, 0xd5, 0x17, 0xbe, 0x50, 0x12, 0x4d, 0x5f, 0xd9, 0xb6, 0x7e, 0x21, 0x31, 0x1c,
	0x63, 0x1c, 0xf0, 0x50, 0x52, 0xd7, 0x63, 0x9c, 0xca, 0x45, 0x84, 0xc9, 0x76, 0x59, 0xde, 0xf2,
	0x52, 0x82, 0x52, 0x9a, 0xf7, 0x50, 0xeb, 0x87, 0x12, 0x63, 0x36, 0x71, 0x79, 0xe8, 0xa0, 0xcf,
	0x13, 0x89, 0xf1, 0xa3, 0x8a, 0x23, 0x55, 0xc8, 0xe3, 0x1c, 0x43, 0x59, 0xd3, 0x1b, 0xfa, 0x55,
	0xd1, 0xc9, 0x06, 0x42, 0xc0, 0x08, 0x30, 0x10, 0xb5, 0x9c, 0x12, 0xd5, 0xbb, 0xd9, 0x83, 0xfa,
	0x9e, 0x32, 0x0a, 0xe3, 0xbf, 0x72, 0x5e, 0xe1, 0x6c, 0xcf, 0xb1, 0x53, 0xdb, 0x16, 0xd1, 0x39,
	0x44, 0x9c, 0xb4, 0xcf, 0xad, 0xec, 0x06, 0xd6, 0x91, 0xbb, 0x6b, 0x2c, 0xbf, 0x2e, 0xb5, 0xe3,
	0x84, 0x7f, 0x07, 0x09, 0xef, 0x50, 0xd9, 0xff, 0xc9, 0xe0, 0x77, 0x6c, 0x4a, 0x6e, 0xc1, 0x48,
	0xef, 0xa4, 0xf0, 0xa5, 0x76, 0xe3, 0x37, 0x7e, 0x67, 0xb5, 0x86, 0x8b, 0x08, 0x1d, 0xe5, 0x6e,
	0x52, 0x30, 0xd2, 0x89, 0x9c, 0xc2, 0x7f, 0xc7, 0x7e, 0xe8, 0x3f, 0x0d, 0x6d, 0xa7, 0xac, 0x91,
	0x12, 0xc0, 0x68, 0xb0, 0x9b, 0x75, 0x52, 0x84, 0xbc, 0xfd, 0x6c, 0x0f, 0x86, 0xe5, 0x5c, 0xb7,
	0xb7, 0x5c, 0x9b, 0xfa, 0x6a, 0x6d, 0xea, 0xdf, 0x6b, 0x53, 0xff, 0xd8, 0x98, 0xda, 0x6a, 0x63,
	0x6a, 0x9f, 0x1b, 0x53, 0x7b, 0xb9, 0xf6, 0xb9, 0x9c, 0xcc, 0x3c, 0x8b, 0x89, 0x80, 0x32, 0x91,
	0x04, 0x22, 0xa1, 0xdc, 0x63, 0x37, 0x6e, 0x14, 0x25, 0x34, 0x10, 0xe3, 0xd9, 0x1b, 0x26, 0x69,
	0x6b, 0x59, 0x9b, 0x5e, 0x41, 0x95, 0xd7, 0xf9, 0x09, 0x00, 0x00, 0xff, 0xff, 0x6d, 0xe9, 0xc8,
	0xf2, 0x20, 0x02, 0x00, 0x00,
}

func (m *InterchainRegisterPacket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InterchainRegisterPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InterchainRegisterPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Event) > 0 {
		i -= len(m.Event)
		copy(dAtA[i:], m.Event)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Event)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *InterchainUnregisterPacket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InterchainUnregisterPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InterchainUnregisterPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Event) > 0 {
		i -= len(m.Event)
		copy(dAtA[i:], m.Event)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Event)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *InterchainEventPacket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InterchainEventPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InterchainEventPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.Event.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintPacket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *InterchainPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InterchainPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InterchainPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Type != 0 {
		i = encodeVarintPacket(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPacket(dAtA []byte, offset int, v uint64) int {
	offset -= sovPacket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *InterchainRegisterPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Event)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *InterchainUnregisterPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Event)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *InterchainEventPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Event.Size()
	n += 1 + l + sovPacket(uint64(l))
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *InterchainPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovPacket(uint64(m.Type))
	}
	return n
}

func sovPacket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPacket(x uint64) (n int) {
	return sovPacket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *InterchainRegisterPacket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InterchainRegisterPacket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InterchainRegisterPacket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Event", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Event = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InterchainUnregisterPacket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InterchainUnregisterPacket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InterchainUnregisterPacket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Event", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Event = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InterchainEventPacket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InterchainEventPacket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InterchainEventPacket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Event", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Event.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InterchainPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InterchainPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InterchainPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= InterchainPacketAck_Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPacket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPacket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPacket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPacket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPacket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPacket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPacket = fmt.Errorf("proto: unexpected end of group")
)
